openapi: 3.0.0
info:
  title: AI News Demo API
  version: "1.0"
  description: A demo API that provides example AI news articles.
servers:
  - url: https://raw.githubusercontent.com/mjschindler/ai-news-demo/main
paths:
  /ai-news.json:
    get:
      summary: Get AI news articles
      responses:
        "200":
          description: A list of AI news articles.
          content:
            application/json:
              schema:
                type: object
                properties:
                  industry:
                    type: string
                  date:
                    type: string
                  articles:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        summary:
                          type: string
                        url:
                          type: string
